# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 882ae773684924f16af70e30ca57f76b0e849e695c760ec59e9fc648fe3133e323beda80861263a31dd0457c614a64b3436d723e1f0f8b5559e8c6f54f95cc99

test:
  secret_key_base: e72edbbba85870093b526c5a789be171bfa30baa63e3173418d9c34eddc42a1d7da73b59f96e8443cca40b9ef940352ddcbe88f804e455fa1b16abe9263bb622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
